# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='first_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contributor',
            name='last_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
