# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160326_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.URLField(blank=True),
        ),
    ]
